"""cria tabelas iniciais vagas curriculos analises

Revision ID: c64462c5cbf6
Revises: 
Create Date: 2026-03-28 14:16:30.568659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64462c5cbf6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_analises_curriculo_id', 'analises', ['curriculo_id'], unique=False)
    op.create_index('ix_analises_score', 'analises', ['score'], unique=False)
    op.create_index('ix_curriculos_status', 'curriculos', ['status'], unique=False)
    op.create_index('ix_curriculos_vaga_id', 'curriculos', ['vaga_id'], unique=False)
    op.create_index('ix_vagas_titulo', 'vagas', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vagas_titulo', table_name='vagas')
    op.drop_index('ix_curriculos_vaga_id', table_name='curriculos')
    op.drop_index('ix_curriculos_status', table_name='curriculos')
    op.drop_index('ix_analises_score', table_name='analises')
    op.drop_index('ix_analises_curriculo_id', table_name='analises')
    # ### end Alembic commands ###
